# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Planguard < Formula
  desc "Pre-plan Terraform security scanner"
  homepage "https://github.com/jonathanhle/planguard"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jonathanhle/planguard/releases/download/v0.1.3/terraform-planguard_0.1.3_darwin_amd64.tar.gz"
      sha256 "dd8a55b441ab428ab0238cb4cfe14358ef54c2c2c6e2041ac2861f20ad52dc88"

      def install
        bin.install "planguard"
      end
    end
    on_arm do
      url "https://github.com/jonathanhle/planguard/releases/download/v0.1.3/terraform-planguard_0.1.3_darwin_arm64.tar.gz"
      sha256 "d4e3c44b0683405cb8cb7e9e4210af0df307c27bab2499cc7fca759d019bcf79"

      def install
        bin.install "planguard"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jonathanhle/planguard/releases/download/v0.1.3/terraform-planguard_0.1.3_linux_amd64.tar.gz"
        sha256 "ba1b38baa25d9e6aba85a505dd5e28919df8f10077d0e8333048b3cf941d92ef"

        def install
          bin.install "planguard"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jonathanhle/planguard/releases/download/v0.1.3/terraform-planguard_0.1.3_linux_arm64.tar.gz"
        sha256 "b96c7e2731517891e4e150ca338c99e020cbe9363f3fb0abcaf4fc2817355885"

        def install
          bin.install "planguard"
        end
      end
    end
  end
end
