# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Planguard < Formula
  desc "Pre-plan Terraform security scanner"
  homepage "https://github.com/jonathanhle/planguard"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jonathanhle/planguard/releases/download/v0.1.1/terraform-planguard_0.1.1_darwin_amd64.tar.gz"
      sha256 "d352533dc3d1b9cc1f340aed0d604bd9eea3a0602336c37c89d9b5f54d707015"

      def install
        bin.install "planguard"
      end
    end
    on_arm do
      url "https://github.com/jonathanhle/planguard/releases/download/v0.1.1/terraform-planguard_0.1.1_darwin_arm64.tar.gz"
      sha256 "09b88be6a8f38810a153a0323caacf6bd29534f845674815f4d73849e055ac5b"

      def install
        bin.install "planguard"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jonathanhle/planguard/releases/download/v0.1.1/terraform-planguard_0.1.1_linux_amd64.tar.gz"
        sha256 "d9829c8f06984d0a75d599c5246197c8a9a97f58307df6ab46945262bc265a43"

        def install
          bin.install "planguard"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jonathanhle/planguard/releases/download/v0.1.1/terraform-planguard_0.1.1_linux_arm64.tar.gz"
        sha256 "ff7d39031a7ffcae6c598ed4782753cab7ed196f6a065e15854d24035dc17b49"

        def install
          bin.install "planguard"
        end
      end
    end
  end
end
