# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Planguard < Formula
  desc "Pre-plan Terraform security scanner"
  homepage "https://github.com/jonathanhle/planguard"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jonathanhle/planguard/releases/download/v0.1.2/terraform-planguard_0.1.2_darwin_amd64.tar.gz"
      sha256 "96b8502d25683751352f9750f0a54cb5cc05b538ced702f1d93fb5cf14e9ada0"

      def install
        bin.install "planguard"
      end
    end
    on_arm do
      url "https://github.com/jonathanhle/planguard/releases/download/v0.1.2/terraform-planguard_0.1.2_darwin_arm64.tar.gz"
      sha256 "1bc4f072ffb696791348dc9a7d68a0bf25f44887f77402f42ba9f1403b28ec08"

      def install
        bin.install "planguard"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jonathanhle/planguard/releases/download/v0.1.2/terraform-planguard_0.1.2_linux_amd64.tar.gz"
        sha256 "7984e85c57a5f108be653e278ca0d3797304748a4431410e912bd0006572900b"

        def install
          bin.install "planguard"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jonathanhle/planguard/releases/download/v0.1.2/terraform-planguard_0.1.2_linux_arm64.tar.gz"
        sha256 "93749378a91557304a314cd99d8193fa49fb2379956fec4bde1e925e12436b5c"

        def install
          bin.install "planguard"
        end
      end
    end
  end
end
